version: '3.9'
services:
  nifi:
    image: apache/nifi:1.19.0
    user: root
    environment: 
      NIFI_WEB_HTTP_PORT: 8080
      NIFI_WEB_HTTP_HOST: 0.0.0.0
    ports: 
      - 8080:8080
    volumes: 
      - ./nifi/conf/:/opt/nifi/nifi-current/conf/
      - ./nifi/driver:/opt/nifi/nifi-current/driver 
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 123456
      PGDATA: /data/postgres
    volumes:
       - ./postgres:/data/postgres
    ports:
      - "5433:5432"
    command: ["postgres", "-c", "log_statement=all"]
  pgadmin:
    image: dpage/pgadmin4:6.19
    environment: 
      PGADMIN_DEFAULT_EMAIL: test@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - "8081:80"
