version: '3.9'
services:
  nifi:
    container_name: nifi-test-1
    image: apache/nifi:1.19.0
    user: root
    environment: 
      NIFI_WEB_HTTP_PORT: 8080
      NIFI_WEB_HTTP_HOST: 0.0.0.0
    ports: 
      - 8080:8080
    volumes: 
      - ./nifi/conf/:/opt/nifi/nifi-current/conf/
      - ./nifi/driver:/opt/nifi/nifi-current/driver 
  postgres:
    container_name: postgres-test-1
    image: postgres:14
    environment:
      POSTGRES_DB: nifi-test
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
      PGDATA: /data/postgres
    volumes:
       - ./postgres/data:/data/postgres
       - ./postgres/sql:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    command: ["postgres", "-c", "log_statement=all"]
  machine-1:
    container_name: machine_1
    image:
  
