nodes = [
	{ :hostname=>'ubuntu1', :ip => '192.168.62.101', :memory => 2048, :cpu => 2, :boxname => "bento/ubuntu-22.04" },
	{ :hostname=>'ubuntu2', :ip => '192.168.62.102', :memory => 2048, :cpu => 2, :boxname => "bento/ubuntu-22.04" },
	{ :hostname=>'ubuntu3', :ip => '192.168.62.103', :memory => 2048, :cpu => 2, :boxname => "bento/ubuntu-22.04" },
]

Vagrant.configure("2") do |config|
	nodes.each do |node|
		config.ssh.username='vagrant'
		config.ssh.password='vagrant'
		config.ssh.insert_key='true'
		config.vm.box_check_update = false
		config.vm.define node[:hostname] do |nodeconfig|
			nodeconfig.vm.box = node[:boxname]
			nodeconfig.vm.hostname = node[:hostname]
			nodeconfig.vm.network :private_network, ip: node[:ip]
			nodeconfig.vm.provider :virtualbox do |vb|
				vb.memory = node[:memory]
				vb.cpus = node[:cpu]
			end
		end
	end
end
